services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: elmokef-db
    environment:
      POSTGRES_DB: elmokef
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: elmokef-redis
    ports:
      - "6379:6379"

  clamav:
    image: clamav/clamav:latest
    container_name: elmokef-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_db:/var/lib/clamav

volumes:
  pgdata:
  clamav_db:
